# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nDisco', models.TextField(max_length=10)),
                ('tipo', models.TextField(blank=True, max_length=10, null=True)),
                ('marca', models.TextField(blank=True, max_length=25, null=True)),
                ('placa', models.TextField(blank=True, max_length=15, null=True)),
                ('modelo', models.TextField(blank=True, max_length=30, null=True)),
                ('cSentados', models.IntegerField(blank=True, max_length=2, null=True)),
                ('cParados', models.IntegerField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
    ]
