# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_auto_20161023_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fechaFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
    ]
